USE [master]
GO

/****** Object:  Database [LendingClub]    Script Date: 10/14/2024 1:36:59 PM ******/
CREATE DATABASE [LendingClub]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LendingClub', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\LendingClub.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LendingClub_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\LendingClub_log.ldf' , SIZE = 2891776KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LendingClub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LendingClub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LendingClub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LendingClub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LendingClub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LendingClub] SET ARITHABORT OFF 
GO

ALTER DATABASE [LendingClub] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LendingClub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LendingClub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LendingClub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LendingClub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LendingClub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LendingClub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LendingClub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LendingClub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LendingClub] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LendingClub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LendingClub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LendingClub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LendingClub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LendingClub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LendingClub] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LendingClub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LendingClub] SET RECOVERY FULL 
GO

ALTER DATABASE [LendingClub] SET  MULTI_USER 
GO

ALTER DATABASE [LendingClub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LendingClub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LendingClub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LendingClub] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LendingClub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LendingClub] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LendingClub] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LendingClub] SET  READ_WRITE 
GO

